name: Build and test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --tag phc-bot

    - name: Run pytest
      run: docker run -v "$PWD:/app" --rm phc-bot pytest -v --cov=phc_bot --cov-report=xml

    - name: Upload code coverage
      if: always()
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: true
        verbose: true

