name: Run bot

on:
  schedule:
    - cron: '0 */1 * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-22.04

    steps:
      - name: Run bot
        id: run
        uses: fjogeleit/http-request-action@v1
        with:
          url: ${{ secrets.HEROKU_APP_URL }}
          method: GET
          timeout: 30000

      - name: Show response
        run: |
          echo ${{ steps.run.outputs.response }}
          echo ${{ steps.run.outputs.headers }}
